name: Manual_4

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Auto Pull Request
        title: Your desired title
        body: Auto-created Pull Request
        branch: release # The branch where you commit
        base: manual_wf-test-1 # Don't forget to specify the right base branch here
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
